name: Using Actions

on:
  push:
    branches:
      - main
      - 'feature/**' # double * to match more than one / like feature/a/b
      - '!featch/kav'
    tags:
      - v1.*
    # paths: 
    # paths-ignore:
    #   - 'docs/**'
  repository_dispatch:
    types: [build]
  # schedule:
  #   - cron: "0/5 * * * *" # runs every 5 mins -> the min time github can repeat as of 12/08/2022
  # push:
  pull_request:
    types: [closed, assigned, opened, reopened]

env:
  WF_ENV: Workflow env

jobs:
  use-actions:
    runs-on: ubuntu-latest
    env:
      JOB_ENV: Job env
    steps:
      - name: Payload from repo dispatch
        env:
          STEP_ENV: Step 01 env
        run: |
          echo ${{ github.event.client_payload.env }}
          echo "WF_ENV: ${WF_ENV}"
          echo "JOB_ENV: ${JOB_ENV}"
          echo "STEP_ENV: ${STEP_ENV}"
      - name: Print all ENV values
        run: |
          echo "WF_ENV: ${WF_ENV}"
          echo "JOB_ENV: ${JOB_ENV}"
          echo "STEP_ENV: ${STEP_ENV}"
      - name: Print files
        run: |
          ls -a
          echo $GITHUB_REPOSITORY
          echo $GITHUB_SHA
          echo ${{ github.token }}
      - name: Checkout Actions
        uses: actions/checkout@v1
      - name: Print files after checkout
        run: ls -a
  
  create_issue:
    runs-on: ubuntu-latest
    permissions:
      issues: write 
    steps:
      - name: Push a random file
        run: |
          pwd
          ls -a
          git init
          git remote add origin "https://$GITHUB_ACTOR:${{secrets.GITHUB_TOKEN}}@github.com/$GITHUB_REPOSITORY.git"
          git config --global user.name "my-action-bot"
          git config --global user.email "my-action-bot@kav.com"
          git fetch
          git checkout main
          git branch --set-upstream-to=origin/main
          git pull
          ls -a
          export RANDOM_ENV=$RANDOM
          echo $RANDOM_ENV
          echo $RANDOM_ENV >> random.txt
          ls -a
          git add -A
          git commit -m "Random file"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
      # - name: Create issue using REST API
      #   run: |
      #     curl --request POST \
      #     --url https://api.github.com/repos/${{ github.repository }}/issues \
      #     --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
      #     --header 'content-type: application/json' \
      #     --data '{
      #       "title": "Automated issue for commit: ${{ github.sha }}",
      #       "body": "This issue was automatically created by the GitHub Action workflow **${{ github.workflow }}**. \n\n The commit hash was: _${{ github.sha }}_."
      #       }' \
      #     --fail