name: Using Actions

on:
  push:
    branches:
      - main
      - 'feature/**' # double * to match more than one / like feature/a/b
      - '!featch/kav'
    tags:
      - v1.*
    # paths: 
    # paths-ignore:
    #   - 'docs/**'
  repository_dispatch:
    types: [build]
  # schedule:
  #   - cron: "0/5 * * * *" # runs every 5 mins -> the min time github can repeat as of 12/08/2022
  # push:
  pull_request:
    types: [closed, assigned, opened, reopened]

env:
  WF_ENV: Workflow env

jobs:
  use-actions:
    runs-on: ubuntu-latest
    env:
      JOB_ENV: Job env
    steps:
      - name: Payload from repo dispatch
        env:
          STEP_ENV: Step 01 env
        run: |
          echo ${{ github.event.client_payload.env }}
          echo "WF_ENV: ${WF_ENV}"
          echo "JOB_ENV: ${JOB_ENV}"
          echo "STEP_ENV: ${STEP_ENV}"
      - name: Print all ENV values
        run: |
          echo "WF_ENV: ${WF_ENV}"
          echo "JOB_ENV: ${JOB_ENV}"
          echo "STEP_ENV: ${STEP_ENV}"
      - name: Print files
        run: |
          ls -a
          echo $GITHUB_REPOSITORY
          echo $GITHUB_SHA
          echo ${{ github.token }}
      - name: Checkout Actions
        uses: actions/checkout@v1
      - name: Print files after checkout
        run: ls -a
      