name: Using Actions

on:
  repository_dispatch:
    types: [build]
  # schedule:
  #   - cron: "0/5 * * * *" # runs every 5 mins -> the min time github can repeat as of 12/08/2022
  # push:
  pull_request:
    types: [closed, assigned, opened, reopened]

jobs:
  use-actions:
    runs-on: ubuntu-latest
    steps:
      - name: Payload from repo dispatch
        run: echo ${{ github.event.client_payload.env }}
      - name: Print all ENV values
        run: env
      - name: Print files
        run: |
          ls -a
          echo $GITHUB_REPOSITORY
          echo $GITHUB_SHA
          echo ${{ github.token }}
      - name: Checkout Actions
        uses: actions/checkout@v1
      - name: Print files after checkout
        run: ls -a
      