name: Run Shell file

on: push

jobs:
  shell-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run a script file
        run: sh ./shell.sh Kaveh
  shell-script2:
    runs-on: ubuntu-latest
    needs:
      - shell-script
    steps:
      - uses: actions/checkout@v3
      - name: Run a script file
        run: sh ./shell.sh Kaveh
